###
# @Authoriztion Code
POST http://localhost:8080/oauth2/authorize
Content-Type: application/x-www-form-urlencoded

response_type=code&client_id=client-id&redirect_uri=http://localhost:8080/profiles/me
