logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug
    io.github.syakuis.idp: trace
server:
  port: 8081
  forward-headers-strategy: native
spring:
  application:
    name: idp-demo
  config:
    import:
      - classpath:properties/idp.yml
  banner:
    location: classpath:io/github/syakuis/idp/core/banner.txt
  main:
    banner-mode: console
  messages:
    basename: i18n/message
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    favicon:
      requestMapping: favicon.ico