name: identity-provider-ci

on:
  push:
    branches:
      - '*'
      - '!deployment'
env:
  SERVICE_NAME: 'identity-provider'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            -Pspring.profiles.active=test
            build